PUSHD ..
call setup.cmd
POPD

set PYTHONPATH=%AF_ROOT%\bin_pyaf\2.6.6;%PYTHONPATH%

set HOUDINI_LOCATION=C:\Program Files\Side Effects Software\Houdini 11.0.775

if exist override.cmd call override.cmd

set HOUDINI_CGRU_PATH=%CGRU_LOCATION%\plugins\houdini

set HOUDINI_AF_PATH=%AF_ROOT%\plugins\houdini

set HOUDINI_AF_OTLSCAN_PATH=%HOUDINI_AF_PATH%;%HOUDINI_LOCATION%\houdini\otls

set PYTHONPATH=%HOUDINI_AF_PATH%;%PYTHONPATH%

IF DEFINED HOUDINI_OTLSCAN_PATH (
   set HOUDINI_OTLSCAN_PATH=%HOUDINI_AF_OTLSCAN_PATH%;%HOUDINI_OTLSCAN_PATH%
) ELSE (
   set HOUDINI_OTLSCAN_PATH=%HOUDINI_AF_OTLSCAN_PATH%
)

set PATH=%HOUDINI_LOCATION%/bin;%PATH%
