FROM cgru/afcommon:2.1.0-ubuntu-14.04

LABEL maintainer="Alexandre Buisine <alexandrejabuisine@gmail.com>"
LABEL cgru_container_version="1.3.0"

ENV AF_SERVER_WAIT="yes"

CMD ["/opt/cgru/afanasy/bin/afrender"]