FROM cgru/afcommon:2.2.1-ubuntu-14.04

LABEL maintainer="Alexandre Buisine <alexandrejabuisine@gmail.com>"
LABEL cgru_container_version="1.0.0"

ENV AF_SERVER_WAIT="yes"

CMD ["/opt/cgru/afanasy/bin/afrender"]