SET AF_ROOT=%CD%
SET AF_PYTHON=%AF_ROOT%\bin;%AF_ROOT%\python
SET PYTHONPATH=%AF_PYTHON%;%PYTHONPATH%

rem SET AF_USERNAME=%USERNAME%
rem SET AF_HOSTNAME=%COMPUTERNAME%

SET PATH=%AF_ROOT%\bin;%PATH%
