#!/bin/bash

echo "Afanasy server POST INSTALL"

if ! id render; then
	if getent group render; then
		useradd render -g render -m
	else
		useradd render -m
	fi
fi

systemctl enable /opt/cgru/afanasy/systemd/afserver.service || true
systemctl daemon-reload || true
systemctl start afserver.service || true

exit 0

