PUSHD ..\..
call setup.cmd
POPD

set HOUDINI_LOCATION=c:\cg\soft\Houdini10

if exist override.cmd call override.cmd

set HOUDINI_CGRU_VERVION=10
set HOUDINI_CGRU_PATH=%AF_ROOT%\plugins\houdini\houdini%HOUDINI_CGRU_VERVION%

set HOUDINI_CGRU_OTLSCAN_PATH=%HOUDINI_CGRU_PATH%\otls;%HOUDINI_LOCATION%\houdini\otls

IF DEFINED HOUDINI_OTLSCAN_PATH (
   set HOUDINI_OTLSCAN_PATH=%HOUDINI_CGRU_OTLSCAN_PATH%;%HOUDINI_OTLSCAN_PATH%
) ELSE (
   set HOUDINI_OTLSCAN_PATH=%HOUDINI_CGRU_OTLSCAN_PATH%
)
