#!/bin/bash

# Make release with Maya binaries only

dest=$1
[ -d "$dest" ] || exit 1

# Remove binaries:
rm -rf $dest/afanasy/bin*
bins="convert exrjoin ffmpeg"
for bin in $bins; do
   rm -f $dest/bin/$bin
done
