#!/bin/bash

# Make release with binaries for Windows64

dest=$1
[ -d "$dest" ] || exit 1

# Clear Software locations:
rm -fv $dest/software_setup/locate_*

# Clear Python:
python=$dest/python
cd $python
echo "Clearing python in '$PWD'"
find -type f -name *.pyc -exec rm -vf {} \;
find -type d -name __pycache__ -exec rm -rvf {} \;
exit 0
