#!/bin/bash

# Make release with binaries for Windows64

dest=$1
[ -d "$dest" ] || exit 1

# Clear Software locations:
rm -fv $dest/software_setup/locate_*

# Clear Python:
echo "Clearing python in '$dest'"
find "${dest}" -type f -name *.pyc -exec rm -vf {} \;
find "${dest}" -type d -name __pycache__ -exec rm -rvf {} \;
exit 0
