#!/bin/bash

echo "Afanasy render POST INSTALL"

id render || useradd render -m

systemctl enable /opt/cgru/afanasy/daemon/afrender.service || true
systemctl daemon-reload || true
systemctl start afrender.service || true

exit 0

