---
name: clang-format Check
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - afanasy
          - rules
          - lib
    steps:
      - uses: actions/checkout@v4
      - name: clang-format Check
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: "19"
          check-path: ${{ matrix.path }}
          include-regex: '^.*\.((((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(ino|pde|proto|cu|js))$'
